### ISSUE TITLE
Update parent hub site membership indicator copy on project sites, or make it customizable per-hub

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/jekyll-theme-open-project#18]
Currently the sites display "A project done by Ribose Open" (at the hero image and footer) but it doesn't sound right in English.

@drystone suggested "[projectname] is Ribose Open" which is better. Thoughts? 

CC: @dewyatt @opoudjis @ribose-jeffreylau

**Comment by strogonoff** [comment]
Yep, sounded awkward to me too! The new phrasing sounds OK

**Comment by strogonoff** [comment]
This is what it would look like when live:

<img width="1404" alt="screen shot 2018-07-20 at 12 52 36 pm" src="https://user-images.githubusercontent.com/292959/42985496-d1dfc3d0-8c1b-11e8-8f22-bd6b9d09e5e2.png">

<img width="1404" alt="screen shot 2018-07-20 at 12 52 28 pm" src="https://user-images.githubusercontent.com/292959/42985502-d81f1796-8c1b-11e8-9645-28ccd5889070.png">

This or “part of” appear better than “done by” but can’t we just leave parent hub logo on its own there, if we don’t need to precisely specify the relationship between the project & its parent hub?

Speaking of the footer, I am not sure if we can write “Copyright © <Project Name>” unless e.g. _Metanorma Inc._ actually exists. I’m not a lawyer, but all instances of open-source project copyrights I see reference legal entities (e.g., React site references Facebook and Django references their non-profit DSF). If that’s how it works then we should reference parent hub by default in copyright assignment.

**Comment by ronaldtse** [comment]
Correct, please refer to “Ribose Group Inc.” the legal entity. Thanks! This looks great!
