### ISSUE TITLE
Implement `featured_with_priority: <int>` for projects on hub site

### ISSUE THREAD

**Issue by strogonoff** [riboseinc/jekyll-theme-open-project#31]
* This would allow to order featured projects on open hub home, similarly to how software/spec ordering works on project sites.
* This would replace the `featured` boolean currently existing. Given lack of adoption we may be able to get away with a breaking change instead of deprecation timeline 😂

**Comment by ronaldtse** [comment]
Agree, and even better if this attribute is done in pure YAML rather than Jekyll-processed Markdown front matter :wink:

**Comment by strogonoff** [comment]
Done a while ago, this one.
