### ISSUE TITLE
Implement narrow screen styling in accordance with mobile design mock-ups

### ISSUE THREAD

**Issue by strogonoff** [riboseinc/jekyll-theme-open-project#32]
Ricardo’s mobile screen mock-ups reside at https://github.com/riboseinc/open-design/tree/master/screen-mockups.

**Comment by ronaldtse** [comment]
Thanks for the awesome work!

There might be some minor adjustments, such as the "Get Started" and "Samples" buttons being too close vertically. But the rest is really nice. Perhaps the hamburger menu can be a bit larger (i.e. the whole top right corner) too.

**Comment by strogonoff** [comment]
@ronaldtse 

> Thanks for the awesome work!

Happy to be helping you out with this!

> There might be some minor adjustments

Absolutely. There’re a few more UI inconsistencies and a couple of bugs to address before issue is closed.

Maybe you could take a look at Metanorma colors though? I think @riksalazar is still waiting for your choice. I implemented a hidden color switcher to preview colors under consideration on live metanorma.com (see https://github.com/riboseinc/metanorma.com/issues/17).

**Comment by ronaldtse** [comment]
Out of 0, a and c, maybe C for now?

**Comment by strogonoff** [comment]
Narrow screens work sufficiently well now per WebKit-based testing. Some examples:

Metanorma | Ribose Open
---|---
![metanorma com_4001_ pixel 2](https://user-images.githubusercontent.com/292959/47419139-203dc300-d7ae-11e8-8432-6f651a6971e8.png) |![open-hub local_4000_ pixel 2](https://user-images.githubusercontent.com/292959/47419142-22078680-d7ae-11e8-9b25-cc906fc21ba6.png)

**Comment by ronaldtse** [comment]
@strogonoff thank you very, very much -- this looks so much nicer!
