### ISSUE TITLE
Rename to jekyll-theme-open-project

### ISSUE THREAD

**Issue by strogonoff** [riboseinc/jekyll-theme-open-project#6]
I noticed that my original intention was to name the theme “Open Project” rather than “Open Hub”, but it got mixed up during gem publication. I believe Open Project is more precise. However, I’m not certain it matters enough to justify the switch.

**Comment by ronaldtse** [comment]
@strogonoff the switch at this point, where it's not actually in production, is totally fine. Let's do the change.

**Comment by strogonoff** [comment]
Renamed GitHub repo and published new gem as [jekyll-theme-open-hub](https://rubygems.org/gems/jekyll-theme-open-project).

**Comment by ronaldtse** [comment]
Thanks @strogonoff !
