### ISSUE TITLE
Keep project data in dotfiles in corresponding project repos and pull it during site build

### ISSUE THREAD

**Issue by strogonoff** [riboseinc/jekyll-theme-open-project#7]
Currently project data in YAML format must be included in project site source, and additionally duplicated in hub site source.

What we could instead do is the following approach:

* Keep structured project data in a dotfile `.open-project.yml` in project source repository root. This seems fairly convenient and is similar to, e.g., how Gitlab pulls its CI configuration. I believe GitHub Pages does a similar thing.
* In hub site and project sites configuration, simply link to the repos. Let the site build process (could be done within a Jekyll plugin) pull that data and generate static pages similar to the existing structure or in accordance with the designs.

Proper implementation here would likely also deal with #2 in one blow.

**Comment by ronaldtse** [comment]
Yes this works indeed. The only issue is that the hub pages need to be rebuilt whenever a project site gets updated, but that's a given due to the role of the hub pages.

**Comment by strogonoff** [comment]
@ronaldtse yeah, this implies some hook to trigger site suite to be rebuilt whenever `.open-project.yml` gets updated, and we would want to be more efficient and avoid rebuilding sites for projects which data was not modified.

Seems like it’s doable with CI: trigger project site build when a specified branch is updated, and trigger hub site build when that branch is updated in any of project repos. There may be a bit of duplication where we’ll have to link to same list of project source repos in (1) hub site Jekyll plugin configuration, and (2) hub site CI configuration, but that doesn’t seem especially dire.

**Comment by ronaldtse** [comment]
Yes, we can even just do `git submodule` of project sites within the hub site repo. And all we need is to update the `config.yml` file to include those posts (I think...).

**Comment by strogonoff** [comment]
I guess we have two options:

1. Configure hub site with links to project repos, and let build process pull the data from those repos, possibly specific branches. (IMO instead of having an “open project site” repo for each project we could use a branch inside actual project codebase repos and keep the data there.)
2. Submodule project site data. I’m not sure if we’ll be able to submodule a specific branch (it seems [a bit messy](https://stackoverflow.com/a/18797720)), but it’s an option.

I prefer the first one for now.

**Comment by strogonoff** [comment]
This is implemented as of 1.0.0. Current implementation does not involve dotfile per se, but works similarly.

Illustration of current implementation idea (except for the spec fetching part, which is for now conceptual):

![illustrations](https://user-images.githubusercontent.com/292959/42724834-8d2dfe36-87a3-11e8-9e51-7b1b757584f4.png)

**Comment by ronaldtse** [comment]
@strogonoff thanks for the beautiful diagram 😉 

One note that if you have time can you go through our list of repos -- many things (i.e. new/renamed repos) have updated since we first started. Thanks!
